<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'LdcEventListenerConfig\ConfigurationFactory'                   => __DIR__ . '/src/ConfigurationFactory.php',
  'LdcEventListenerConfig\ServiceManagerDelegatorFactoryInjector' => __DIR__ . '/src/ServiceManagerDelegatorFactoryInjector.php',
  'LdcEventListenerConfig\ServiceManagerDelegatorFactory'         => __DIR__ . '/src/ServiceManagerDelegatorFactory.php',
);
